name: "TMS Go Test"
description: "Run test and upload to codecov"
inputs:
  codecov-token:
    description: 'codecov token'
    required: true
  github-token:
    description: 'github token'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    
    - name: "setup private repo access"
      run: |
        export GOPRIVATE=github.com/TemoMailerSolutions/*
        git config --global url."https://${{ inputs.github-token }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
      shell: bash
      
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        
    - name: Test with the Go CLI
      run: go test -v -coverprofile=coverage.out ./...
      shell: bash

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: coverage.out
        token: ${{ inputs.codecov-token }}
